# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #oxr463/setup-leiningen@0.0.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: delete content
        run: rm -rf docs public
      - name: Setup Leiningen
        uses: oxr463/setup-leiningen@0.0.1
        with:
          exec: lein run
      # Runs a set of commands using the runners shell
      - name: rebuild static site
        run: mv public docs
        # run: |
        #  rm -rf docs
        #  lein run
        #  mv public docs
